---
title: "Capstone Project Proposal"
author: "Cesar Escobedo"
date: "March 5, 2018"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Final Capstone Project Proposal


### What is the problem you want to solve? 
   
   Identify the acculturation level of Hispanics by using a different set of variables that can be gathered without the need of running an online survey.

### Who is your client and why do they care about this problem? In other words, what will your client DO or DECIDE based on your analysis that they wouldn’t have otherwise?

  My client would be Market Research and Advertising companies. It would give them the flexibility to target the different levels of acculturation before running an recruitment or Ad campaign and therefore save money with a better audience. 

### What data are you going to use for this? How will you acquire this data?
  
  There are 2 main data sets that I think will helpful and that are available for free:
    
    1. [Pew Research data sets](http://www.pewhispanic.org/datasets/)
    2. [Census data sets](https://www.census.gov/data/datasets.html)

### In brief, outline your approach to solving this problem (knowing that this might change later).

  There are another variables like: **Number of Persons in Household**, **Hosehould Income**, **Zip code**,  etc. That are available in the data sets mentioned above that could provide a pattern to identify the different acculturation levels without the need to ask specifically for the questions that at this time are used to assign a level.

### What are your deliverables? Typically, this would include code, along with a paper and/or a slide deck.

  A paper explaining the methods used to create a pattern among the different variables and the acculturation level assigned and the code used to get the final results.